#----------------------------------------------------------------
# file:    Makefile
# date:    2016-02-05
# author:  paul.dautry
# purpose:
#       This file is used call the script making the challenge
#----------------------------------------------------------------

all:
	./build.sh        
